name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - 
      uses: actions/checkout@v2
    - 
      name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - 
      name: Install dependencies
      run: dotnet restore
    - 
      name: Build
      run: dotnet build --configuration Release --no-restore
    - 
      name: Test
      run: dotnet test --no-restore --verbosity normal 
    -
      name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
    - name: Push to DigitalOcean
      uses: docker/build-push-action@v1
      with:
        registry: registry.digitalocean.com
        repository: manistra/manistra
        tag_with_ref: true  
